sudo: required
dist: bionic
language: cpp

os:
  - linux

compiler:
  - g++

before_install:
  # C++17 g++ 9.2.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17 g++ 9.2.1
  - sudo apt-get install -qq g++-9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
